name: CI

on:
  push:
    branches: ["main"]

env:
  # Isso remove o aviso de depreciação forçando o Node 24
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        # O --if-present garante que o erro 127 não aconteça se o script não existir
        run: npm test --if-present
